import React, { useState } from "react";
import { RadialBarChart, RadialBar } from "recharts";
import jsPDF from "jspdf";
import Footer from "../components/Footer";

export default function PredictPage() {

  const [form, setForm] = useState({
    name: "",
    age: "",
    gender: "male",

    creatinine: "",
    blood_urea: "",
    egfr: "",
    urine_albumin: "",

    sodium: "",
    potassium: "",
    calcium: "",
    phosphorus: "",
    hemoglobin: ""
  });

  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleChange = (e) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value
    });
  };

  // ======================
  // AI Prediction
  // ======================

  const predict = async () => {

    setLoading(true);

    await new Promise((res) => setTimeout(res, 1500));

    const creatinine = parseFloat(form.creatinine || 1);
    const urea = parseFloat(form.blood_urea || 20);
    const hb = parseFloat(form.hemoglobin || 13);
    const egfr = parseFloat(form.egfr || 90);
    const albumin = parseFloat(form.urine_albumin || 0);

    let risk = Math.min(
      100,
      Math.round(
        creatinine * 20 +
        urea * 0.4 +
        (13 - hb) * 4 +
        albumin * 0.3 +
        (90 - egfr) * 0.5
      )
    );

    let stage = "G1";

    if (risk > 80) stage = "G5";
    else if (risk > 65) stage = "G4";
    else if (risk > 50) stage = "G3";
    else if (risk > 30) stage = "G2";

    let level = "Low";

    if (risk > 70) level = "High";
    else if (risk > 40) level = "Moderate";

    const recommendations = {
      Low: "Kidney function appears normal. Maintain a healthy lifestyle.",
      Moderate: "Monitor kidney function regularly and consult a doctor.",
      High: "High risk detected. Immediate nephrologist consultation recommended."
    };

    setResult({
      risk,
      stage,
      level,
      recommendations: recommendations[level]
    });

    setLoading(false);
  };

  // ======================
  // PDF Export
  // ======================

  const exportPDF = () => {
  if (!result) return;

  const doc = new jsPDF();

  // ================= HEADER =================
  doc.setFillColor(39, 70, 144); // #274690
  doc.rect(0, 0, 210, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text("KidneyAI Medical Report", 20, 18);

  // ================= PATIENT INFO =================
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);

  doc.text("Patient Information", 20, 45);

  doc.setDrawColor(200);
  doc.rect(20, 50, 80, 30);

  doc.text(`Name: ${form.name}`, 25, 60);
  doc.text(`Age: ${form.age}`, 25, 68);
  doc.text(`Gender: ${form.gender}`, 25, 76);

  // ================= LAB RESULTS =================
  doc.text("Lab Results", 20, 95);

  doc.rect(20, 100, 80, 80);

  let y = 110;

  const labData = [
    ["Creatinine", form.creatinine],
    ["Blood Urea", form.blood_urea],
    ["eGFR", form.egfr],
    ["Urine Albumin", form.urine_albumin],
    ["Sodium", form.sodium],
    ["Potassium", form.potassium],
    ["Calcium", form.calcium],
    ["Phosphorus", form.phosphorus],
    ["Hemoglobin", form.hemoglobin],
  ];

  labData.forEach(([key, val]) => {
    doc.text(`${key}: ${val}`, 25, y);
    y += 7;
  });

  // ================= AI RESULT =================
  doc.text("AI Diagnosis", 120, 45);

  doc.setFillColor(245, 247, 255);
  doc.rect(120, 50, 70, 50, "F");

  doc.text(`Risk: ${result.risk}%`, 125, 65);
  doc.text(`Stage: ${result.stage}`, 125, 75);
  doc.text(`Level: ${result.level}`, 125, 85);

  // ================= RECOMMENDATION =================
  doc.text("Recommendations", 120, 115);

  doc.setFillColor(230, 240, 255);
  doc.rect(120, 120, 70, 40, "F");

  const splitText = doc.splitTextToSize(result.recommendations, 60);
  doc.text(splitText, 125, 130);

  // ================= FOOTER =================
  doc.setFontSize(10);
  doc.setTextColor(150);

  doc.text(
    "This report is generated by AI and should not replace medical diagnosis.",
    20,
    280
  );

  doc.text(`Date: ${new Date().toLocaleDateString()}`, 150, 280);

  doc.save("-Report.pdf");
};

  return (
    <>
    
{/* ================= FORM ================= */}

{!result && (

<section className="min-h-screen bg-[#f4f7ff] py-16 px-6">

<div className="max-w-5xl mx-auto space-y-8">

{/* Patient Info */}

<div className="bg-white p-8 rounded-2xl shadow">

<h2 className="text-2xl font-bold mb-6 text-[#274690]">
Patient Information
</h2>

<input
name="name"
placeholder="Patient Name"
onChange={handleChange}
className="border p-3 rounded-lg w-full mb-4"
/>

<div className="grid grid-cols-2 gap-4">

<input
name="age"
type="number"
placeholder="Age"
onChange={handleChange}
className="border p-3 rounded-lg"
/>

<select
name="gender"
onChange={handleChange}
className="border p-3 rounded-lg"
>
<option value="male">Male</option>
<option value="female">Female</option>
</select>

</div>

</div>

{/* Kidney Function */}

<div className="bg-white p-8 rounded-2xl shadow">

<h3 className="text-xl font-semibold mb-6 text-[#274690]">
Kidney Function
</h3>

<div className="grid md:grid-cols-2 gap-4">

<input name="creatinine" placeholder="Serum Creatinine (mg/dL)" onChange={handleChange} className="border p-3 rounded-lg" />
<input name="blood_urea" placeholder="Blood Urea Nitrogen (mg/dL)" onChange={handleChange} className="border p-3 rounded-lg" />
<input name="egfr" placeholder="eGFR (mL/min/1.73m²)" onChange={handleChange} className="border p-3 rounded-lg" />
<input name="urine_albumin" placeholder="Urine Albumin (mg/g Cr)" onChange={handleChange} className="border p-3 rounded-lg" />

</div>


</div>

{/* Electrolytes */}

<div className="bg-white p-8 rounded-2xl shadow">

<h3 className="text-xl font-semibold mb-6 text-[#274690]">
Electrolytes & Metabolic
</h3>

<div className="grid md:grid-cols-2 gap-4">

<input name="sodium" placeholder="Sodium (mEq/L)" onChange={handleChange} className="border p-3 rounded-lg" />
<input name="potassium" placeholder="Potassium (mEq/L)" onChange={handleChange} className="border p-3 rounded-lg" />
<input name="calcium" placeholder="Calcium (mg/dL)" onChange={handleChange} className="border p-3 rounded-lg" />
<input name="phosphorus" placeholder="Phosphorus (mg/dL)" onChange={handleChange} className="border p-3 rounded-lg" />
<input name="hemoglobin" placeholder="Hemoglobin (g/dL)" onChange={handleChange} className="border p-3 rounded-lg" />

</div>

{/* ================= Upload Lab Test ================= */}
<div >
  <h3 className="text-xl font-semibold mb-6 text-[#274690]">
    Upload Lab Test
  </h3>

  <input
    type="file"
    accept=".pdf,image/*"
    onChange={(e) => {
      const file = e.target.files[0];
      if (!file) return;
      console.log("Uploaded file:", file.name);
      alert(`File "${file.name}" uploaded successfully!`);
    }}
    className="border p-3 rounded-lg w-full"
  />
</div>

<button
onClick={predict}
className="mt-6 w-full bg-[#274690] text-white py-3 rounded-lg"
>
{loading ? "Analyzing..." : "Run AI Diagnosis"}
</button>

</div>

</div>


</section>

)}

{/* ================= RESULT DASHBOARD ================= */}

{result && (

<section className="min-h-screen bg-gradient-to-r from-blue-50 to-blue-100 p-10">

<div className="max-w-7xl mx-auto space-y-8">

<div className="grid md:grid-cols-2 gap-8">

{/* LEFT */}

<div className="bg-blue-900 text-white p-8 rounded-3xl">

<h2 className="text-2xl font-bold mb-6">Patient Information</h2>

<p>Name: {form.name}</p>
<p>Age: {form.age}</p>
<p>Gender: {form.gender}</p>
<p>Date: {new Date().toLocaleDateString()}</p>

<h2 className="text-2xl font-bold mt-10 mb-4">Lab Results</h2>

<div className="grid grid-cols-2 gap-3 text-sm">

<p>Creatinine: {form.creatinine}</p>
<p>Blood Urea: {form.blood_urea}</p>
<p>eGFR: {form.egfr}</p>
<p>Urine Albumin: {form.urine_albumin}</p>
<p>Sodium: {form.sodium}</p>
<p>Potassium: {form.potassium}</p>
<p>Calcium: {form.calcium}</p>
<p>Phosphorus: {form.phosphorus}</p>
<p>Hemoglobin: {form.hemoglobin}</p>

</div>

</div>

{/* RIGHT */}

<div className="space-y-6">

<div className="bg-white p-8 rounded-3xl shadow">

<h2 className="text-2xl font-bold mb-6 text-[#274690]">
Main Diagnosis
</h2>

<div className="flex items-center gap-6">

<RadialBarChart
width={200}
height={200}
innerRadius="70%"
outerRadius="100%"
data={[{ value: result.risk }]}
startAngle={180}
endAngle={0}
>

<RadialBar dataKey="value" fill="#f59e0b" />

</RadialBarChart>

<div>

<p>Kidney Stage: {result.stage}</p>
<p>Risk Level: {result.level}</p>
<p>Probability: {result.risk}%</p>

</div>

</div>

</div>

<div className="bg-white p-8 rounded-3xl shadow">

<h2 className="text-xl font-bold mb-4 text-[#274690]">
Recommendations
</h2>

<p>{result.recommendations}</p>

</div>

</div>

</div>

<div className="grid md:grid-cols-4 gap-6">  {/* غيّرنا من 3 إلى 4 أعمدة */}

  <button className="bg-blue-700 text-white p-6 rounded-2xl">
    Chat with Medical AI
  </button>

  <button
    onClick={exportPDF}
    className="bg-white shadow p-6 rounded-2xl"
  >
    Generate PDF Report
  </button>

  <button className="bg-blue-800 text-white p-6 rounded-2xl">
    Share Results
  </button>

  {/* ================= New Test Button ================= */}
  <button
    onClick={() => {
      setResult(null); // إعادة النتيجة للقيم الافتراضية
      setForm({
        name: "",
        age: "",
        gender: "male",
        creatinine: "",
        blood_urea: "",
        egfr: "",
        urine_albumin: "",
        sodium: "",
        potassium: "",
        calcium: "",
        phosphorus: "",
        hemoglobin: ""
      });
    }}
    className="bg-green-600 text-white p-6 rounded-2xl"
  >
    New Test
  </button>

</div>

</div>

</section>

)}

<Footer />

</>
  );
}
