import React, { useState } from "react";
import { RadialBarChart, RadialBar } from "recharts";
import jsPDF from "jspdf";
import Footer from "../components/Footer";
import { useNavigate } from "react-router-dom";

export default function PredictPage() {

  const [form, setForm] = useState({
    name: "",
    age: "",
    gender: "male",

    creatinine: "",
    blood_urea: "",
    egfr: "",
    urine_albumin: "",

    sodium: "",
    potassium: "",
    calcium: "",
    phosphorus: "",
    hemoglobin: ""
  });

  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const handleChange = (e) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value
    });
  };

  // ======================
  // AI Prediction
  // ======================

  const predict = async () => {

    setLoading(true);

    await new Promise((res) => setTimeout(res, 1500));

    const creatinine = parseFloat(form.creatinine || 1);
    const urea = parseFloat(form.blood_urea || 20);
    const hb = parseFloat(form.hemoglobin || 13);
    const egfr = parseFloat(form.egfr || 90);
    const albumin = parseFloat(form.urine_albumin || 0);

    let risk = Math.min(
      100,
      Math.round(
        creatinine * 20 +
        urea * 0.4 +
        (13 - hb) * 4 +
        albumin * 0.3 +
        (90 - egfr) * 0.5
      )
    );

    let stage = "G1";

    if (risk > 80) stage = "G5";
    else if (risk > 65) stage = "G4";
    else if (risk > 50) stage = "G3";
    else if (risk > 30) stage = "G2";

    let level = "Low";

    if (risk > 70) level = "High";
    else if (risk > 40) level = "Moderate";

    const recommendations = {
      Low: "Kidney function appears normal. Maintain a healthy lifestyle.",
      Moderate: "Monitor kidney function regularly and consult a doctor.",
      High: "High risk detected. Immediate nephrologist consultation recommended."
    };

    setResult({
      risk,
      stage,
      level,
      recommendations: recommendations[level]
    });

    setLoading(false);
  };

  // ======================
  // PDF Export
  // ======================

 const exportPDF = () => {
  if (!result) return;

  const doc = new jsPDF();

  const egfr = Number(form.egfr);

  const stage =
    egfr < 15 ? 5 :
    egfr < 30 ? 4 :
    egfr < 60 ? 3 :
    egfr < 90 ? 2 : 1;

  const riskLevel =
    egfr < 15 ? "Critical" :
    egfr < 30 ? "High Risk" :
    egfr < 60 ? "Moderate Risk" : "Low Risk";

  // ================= HEADER =================
  doc.setFillColor(39, 70, 144);
  doc.rect(0, 0, 210, 25, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text("KidneyAI Report", 20, 16);

  // ================= PATIENT CARD =================
  doc.setTextColor(0, 0, 0);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(20, 35, 170, 25, 3, 3, "F");

  doc.setFontSize(11);
  doc.text(`Name: ${form.name}`, 25, 45);
  doc.text(`Age: ${form.age}`, 80, 45);
  doc.text(`Gender: ${form.gender}`, 130, 45);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 25, 55);

  // ================= RESULT CARDS =================
  // Stage
  doc.roundedRect(20, 70, 80, 35, 3, 3);
  doc.text("CKD Stage", 25, 80);
  doc.setFontSize(18);
  doc.text(`Stage ${stage}`, 25, 92);

  // Risk
  doc.roundedRect(110, 70, 80, 35, 3, 3);
  doc.setFontSize(11);
  doc.text("Risk Level", 115, 80);
  doc.setFontSize(16);
  doc.text(riskLevel, 115, 92);

  // Progress bar
  doc.setFillColor(220, 220, 220);
  doc.rect(115, 97, 60, 4, "F");

  doc.setFillColor(39, 70, 144);
  doc.rect(115, 97, (result.risk / 100) * 60, 4, "F");

  // ================= INDICATORS =================
  doc.setFontSize(11);
  doc.text("Probability: " + result.risk + "%", 20, 115);
  doc.text("eGFR: " + form.egfr, 80, 115);
  doc.text("Creatinine: " + form.creatinine, 130, 115);

  // ================= LAB RESULTS =================
  doc.roundedRect(20, 125, 170, 60, 3, 3);
  doc.text("Lab Results", 25, 135);

  let y = 145;

  const labData = [
    ["Blood Urea", form.blood_urea],
    ["Urine Albumin", form.urine_albumin],
    ["Sodium", form.sodium],
    ["Potassium", form.potassium],
    ["Calcium", form.calcium],
    ["Phosphorus", form.phosphorus],
    ["Hemoglobin", form.hemoglobin],
  ];

  labData.forEach(([key, val], i) => {
    const x = i % 2 === 0 ? 25 : 110;
    if (i % 2 === 0 && i !== 0) y += 7;

    doc.text(`${key}: ${val}`, x, y);
  });

  // ================= RECOMMENDATIONS =================
  doc.roundedRect(20, 195, 170, 50, 3, 3);
  doc.text("Recommendations", 25, 205);

  const splitText = doc.splitTextToSize(result.recommendations, 160);
  doc.text(splitText, 25, 215);

  // ================= FOOTER =================
  doc.setFontSize(9);
  doc.setTextColor(150);

  doc.text(
    "This report is generated by AI and should not replace medical advice.",
    20,
    285
  );

  doc.text(new Date().toLocaleDateString(), 170, 285);

  doc.save("KidneyAI-Report.pdf");
};

  return (
    <>
    
{/* ================= FORM ================= */}

{!result && (

<section className="min-h-screen bg-[#f4f7ff] py-16 px-6">

<div className="max-w-5xl mx-auto space-y-8">

{/* Patient Info */}

<div className="bg-white p-8 rounded-2xl shadow">

<h2 className="text-2xl font-bold mb-6 text-[#274690]">
Patient Information
</h2>

<input
name="name"
placeholder="Patient Name"
onChange={handleChange}
className="border p-3 rounded-lg w-full mb-4"
/>

<div className="grid grid-cols-2 gap-4">

<input
name="age"
type="number"
placeholder="Age"
onChange={handleChange}
className="border p-3 rounded-lg"
/>

<select
name="gender"
onChange={handleChange}
className="border p-3 rounded-lg"
>
<option value="male">Male</option>
<option value="female">Female</option>
</select>

</div>

</div>

{/* Kidney Function */}

<div className="bg-white p-8 rounded-2xl shadow">

<h3 className="text-xl font-semibold mb-6 text-[#274690]">
Kidney Function
</h3>

<div className="grid md:grid-cols-2 gap-4">

<input name="creatinine" placeholder="Serum Creatinine (mg/dL)" onChange={handleChange} className="border p-3 rounded-lg" />
<input name="blood_urea" placeholder="Blood Urea Nitrogen (mg/dL)" onChange={handleChange} className="border p-3 rounded-lg" />
<input name="egfr" placeholder="eGFR (mL/min/1.73m²)" onChange={handleChange} className="border p-3 rounded-lg" />
<input name="urine_albumin" placeholder="Urine Albumin (mg/g Cr)" onChange={handleChange} className="border p-3 rounded-lg" />

</div>


</div>

{/* Electrolytes */}

<div className="bg-white p-8 rounded-2xl shadow">

<h3 className="text-xl font-semibold mb-6 text-[#274690]">
Electrolytes & Metabolic
</h3>

<div className="grid md:grid-cols-2 gap-4">

<input name="sodium" placeholder="Sodium (mEq/L)" onChange={handleChange} className="border p-3 rounded-lg" />
<input name="potassium" placeholder="Potassium (mEq/L)" onChange={handleChange} className="border p-3 rounded-lg" />
<input name="calcium" placeholder="Calcium (mg/dL)" onChange={handleChange} className="border p-3 rounded-lg" />
<input name="phosphorus" placeholder="Phosphorus (mg/dL)" onChange={handleChange} className="border p-3 rounded-lg" />
<input name="hemoglobin" placeholder="Hemoglobin (g/dL)" onChange={handleChange} className="border p-3 rounded-lg" />

</div>

{/* ================= Upload Lab Test ================= */}
<div >
  <h3 className="text-xl font-semibold mb-6 text-[#274690]">
    Upload Lab Test
  </h3>

  <input
    type="file"
    accept=".pdf,image/*"
    onChange={(e) => {
      const file = e.target.files[0];
      if (!file) return;
      console.log("Uploaded file:", file.name);
      alert(`File "${file.name}" uploaded successfully!`);
    }}
    className="border p-3 rounded-lg w-full"
  />
</div>
<div className="mt-6 grid grid-cols-2 gap-4">

  {/* Run AI Diagnosis */}
  <button
    onClick={predict}
    className="bg-[#274690] text-white py-3 rounded-lg"
  >
    {loading ? "Analyzing..." : "Run AI Diagnosis"}
  </button>

  {/* Next → Smart Alerts */}
  <button
    onClick={() => navigate("/smart-alerts")}
    className="bg-green-600 text-white py-3 rounded-lg"
  >
    Next → Smart Alerts
  </button>

</div>

</div>

</div>


</section>

)}

{/* ================= RESULT DASHBOARD ================= */}

{result && (

<section className="min-h-screen bg-[#f5f7fc] p-10">

<div className="max-w-6xl mx-auto space-y-6">

{/* ✅ Analysis Complete */}
<div className="bg-green-100 text-green-700 p-4 rounded-xl flex justify-between">
  <p className="font-medium">Analysis Complete</p>
  <span>✔</span>
</div>

{/* ================= PATIENT INFO ================= */}
<div className="bg-white p-6 rounded-2xl shadow-sm flex justify-between flex-wrap gap-4">

<div>
  <p className="text-gray-500 text-sm">Name</p>
  <p className="font-bold">{form.name || "—"}</p>
</div>

<div>
  <p className="text-gray-500 text-sm">Age</p>
  <p className="font-bold">{form.age || "—"}</p>
</div>

<div>
  <p className="text-gray-500 text-sm">Gender</p>
  <p className="font-bold">{form.gender}</p>
</div>

<div>
  <p className="text-gray-500 text-sm">Date</p>
  <p className="font-bold">
    {new Date().toLocaleDateString()}
  </p>
</div>

</div>

{/* ================= LOGIC ================= */}
{(() => {
  const egfr = Number(form.egfr);
  const creatinine = Number(form.creatinine);
  const hemoglobin = Number(form.hemoglobin);

  const stage =
    egfr < 15 ? 5 :
    egfr < 30 ? 4 :
    egfr < 60 ? 3 :
    egfr < 90 ? 2 : 1;

  const stageText =
    egfr < 15 ? "Kidney Failure" :
    egfr < 30 ? "Severe decrease" :
    egfr < 60 ? "Moderate decrease" :
    egfr < 90 ? "Mild decrease" : "Normal";

  const riskLevel =
    egfr < 15 ? "Critical" :
    egfr < 30 ? "High Risk" :
    egfr < 60 ? "Moderate Risk" : "Low Risk";

  return (

  <>
  {/* ================= RESULT ================= */}
  <div className="grid md:grid-cols-2 gap-6">

  {/* Stage */}
  <div className="bg-white p-8 rounded-2xl shadow-sm text-center">
    <p className="text-gray-500">CKD Stage</p>
    <h2 className="text-3xl font-bold text-blue-700 mt-2">
      Stage {stage}
    </h2>
    <p className="text-gray-400 mt-2">{stageText}</p>
  </div>

  {/* Risk */}
  <div className="bg-green-100 p-8 rounded-2xl shadow-sm">
    <p className="text-gray-600">Risk Level</p>

    <h2 className={`text-2xl font-bold mt-2 ${
      riskLevel === "Critical"
        ? "text-red-600"
        : "text-green-800"
    }`}>
      {riskLevel}
    </h2>

    <div className="w-full bg-green-200 h-2 rounded-full mt-4">
      <div
        className="bg-green-700 h-2 rounded-full"
        style={{ width: `${result.risk}%` }}
      ></div>
    </div>
  </div>

  </div>

  {/* ================= INDICATORS ================= */}
  <div className="bg-white p-6 rounded-2xl shadow-sm flex justify-between flex-wrap gap-4">

  <div>
    <p className="text-gray-500 text-sm">Probability</p>
    <p className="text-red-500 font-bold">
      {result.risk}%
    </p>
  </div>

  <div>
    <p className="text-gray-500 text-sm">eGFR</p>
    <p className="font-bold">{form.egfr}</p>
  </div>

  <div>
    <p className="text-gray-500 text-sm">Creatinine</p>
    <p className="font-bold">{form.creatinine}</p>
  </div>

  </div>

  {/* ================= LAB RESULTS ================= */}
  <div className="bg-white p-6 rounded-2xl shadow-sm">

  <h3 className="font-bold mb-4 text-gray-700">
    Lab Results
  </h3>

  <div className="grid md:grid-cols-3 gap-4 text-sm text-gray-600">

  <p>Blood Urea: {form.blood_urea}</p>
  <p>Urine Albumin: {form.urine_albumin}</p>
  <p>Sodium: {form.sodium}</p>
  <p>Potassium: {form.potassium}</p>
  <p>Calcium: {form.calcium}</p>
  <p>Phosphorus: {form.phosphorus}</p>
  <p>Hemoglobin: {form.hemoglobin}</p>

  </div>

  </div>

  {/* ================= AI EXPLANATION ================= */}
  <div className="bg-white p-6 rounded-2xl shadow-sm">

  <h3 className="font-bold mb-3 text-gray-700">
    AI Explanation
  </h3>

  <ul className="list-disc pl-5 text-gray-600 space-y-1">

  {creatinine > 5 && (
    <li>Creatinine is very high</li>
  )}

  {egfr < 15 && (
    <li>Severe kidney failure - urgent care needed</li>
  )}

  {hemoglobin < 10 && (
    <li>Possible anemia detected</li>
  )}

  {egfr >= 60 && (
    <li>Kidney function is relatively normal</li>
  )}

  </ul>

  </div>

  </>
  );
})()}

{/* ================= BUTTONS ================= */}
<div className="grid md:grid-cols-3 gap-4">

<button
  onClick={exportPDF}
  className="bg-white shadow-sm p-4 rounded-xl"
>
  Generate PDF
</button>

<button className="bg-blue-800 text-white p-4 rounded-xl">
  Share
</button>

<button
  onClick={() => {
    setResult(null);
    setForm({
      name: "",
      age: "",
      gender: "male",
      creatinine: "",
      blood_urea: "",
      egfr: "",
      urine_albumin: "",
      sodium: "",
      potassium: "",
      calcium: "",
      phosphorus: "",
      hemoglobin: ""
    });
  }}
  className="bg-green-600 text-white p-4 rounded-xl"
>
  New Test
</button>

</div>

</div>
</section>

)}


<Footer />

</>
  );
}
